In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/2024_Imports_HS10_by_Country.csv.xz")
print(df.shape)
print(df.columns.tolist())
df.head()

(671352, 9)
['month', 'hs', 'hs_desc', 'uom', 'country', 'vfd', 'cif', 'qty', 'status']

,month,hs,hs_desc,uom,country,vfd,cif,qty,status
0,202401,101210027,"Horses; live, pure-bred breeding animals, thor...",NMB,Australia,8242,11356,1.0,Final
1,202401,101210041,"Horses; live, pure-bred breeding animals, stan...",NMB,Australia,82419,94875,4.0,Final
2,202401,101290010,"Horses; live, other than pure-bred breeding an...",NMB,Australia,1930612,2045762,21.0,Final
3,202401,101290010,"Horses; live, other than pure-bred breeding an...",NMB,Hong Kong (Special Administrative Region),2400,103200,12.0,Final
4,202401,101290010,"Horses; live, other than pure-bred breeding an...",NMB,New Zealand,27780,30290,1.0,Final

In [3]:
f = Path("../data/raw/2023_Imports_HS10_by_Country.csv.xz")
print(pd.read_csv(f, nrows=0).columns.tolist())
pd.read_csv(f, nrows=3)

['Month', 'Harmonised System Code', 'Harmonised System Description', 'Unit Qty', 'Country', 'Imports ($NZD vfd)', 'Imports ($NZD cif)', 'Imports Qty', 'Status', 'Unnamed: 9']

,Month,Harmonised System Code,Harmonised System Description,Unit Qty,Country,Imports ($NZD vfd),Imports ($NZD cif),Imports Qty,Status,Unnamed: 9
0,202301,101210027,"Horses; live, pure-bred breeding animals, thor...",NMB,Australia,800,"6,235",1,Final,NaN
1,202301,101210041,"Horses; live, pure-bred breeding animals, stan...",NMB,Australia,"42,012","50,382",2,Final,NaN
2,202301,101290010,"Horses; live, other than pure-bred breeding an...",NMB,Australia,"3,062,546","3,140,196",15,Final,NaN